[package]
name = "vayu"
version = "0.1.0"
edition = "2021"
authors = ["Raghav Tirumale raghav.tirumale@gmail.com"]
license = "MIT"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.31"
clap = { version = "4.4.12", features = ["derive"] }
colored = "2.1.0"
indicatif = "0.17.7"
